//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbcheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dbcheck.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(t.table_name), rtrim(t.constraint_name), rtrim(x.column_name), isnull(rtrim(y.column_name), &apos;&apos;), rtrim(x.ordinal_position)
        ///from information_schema.table_constraints t
        ///inner join information_schema.key_column_usage x on t.constraint_name = x.constraint_name
        ///left join information_schema.referential_constraints c on t.constraint_name = c.constraint_name
        ///left join information_schema.key_column_usage y on c.unique_constraint_name = y.constraint_name and x.ordinal_position = y.ordinal_position
        ///w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstraintColumns {
            get {
                return ResourceManager.GetString("ConstraintColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	o.name
        ///FROM 
        ///	sysobjects o 
        ///	INNER JOIN syscolumns c ON o.id = c.cdefault
        ///	INNER JOIN sysobjects t ON c.id = t.id
        ///WHERE 
        ///	o.xtype = &apos;D&apos;
        ///	AND c.name = @ColumnName
        ///	AND t.name = @TableName.
        /// </summary>
        internal static string ConstraintDefault {
            get {
                return ResourceManager.GetString("ConstraintDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	rtrim(t.table_name), 
        ///	rtrim(t.constraint_name), 
        ///	rtrim(t.constraint_type),
        ///	isnull(rtrim(t1.table_name), &apos;&apos;),
        ///	isnull(rtrim([partitionSchema].[partition_schema_name]),&apos;&apos;)	[PartitionScheme]
        ///from 
        ///	information_schema.table_constraints t
        ///left join 
        ///	information_schema.referential_constraints x on x.constraint_name = t.constraint_name
        ///left join 
        ///	information_schema.table_constraints t1 on t1.constraint_name = x.unique_constraint_name
        ///left join
        ///	(
        ///		select 
        ///			t1.name [TableName], 
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constraints {
            get {
                return ResourceManager.GetString("Constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(o.name), c.text
        ///from syscomments c
        ///	inner join sysobjects o on o.id = c.id and o.xtype in (&apos;FN&apos;,&apos;TF&apos;) and o.name not like &apos;dt_%&apos;
        ///where o.name like @prefix
        ///order by c.id, c.colid.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///&apos;INSERT [dbo].[orb_Globalization] ([glo_Interface], [glo_Page], [glo_Control], [glo_Culture], [glo_Text]) VALUES (&apos; + cast([glo_Interface] as varchar) + &apos;, N&apos;&apos;&apos; + [glo_Page] + &apos;&apos;&apos;, N&apos;&apos;&apos; + [glo_Control] + &apos;&apos;&apos;, N&apos;&apos;&apos; +[glo_Culture] + &apos;&apos;&apos;, N&apos;&apos;&apos; + replace([glo_Text], char(39), char(39) + char(39)) + &apos;&apos;&apos;)&apos;
        ///from [orb_Globalization]
        ///order by glo_Interface, glo_Page, glo_Control.
        /// </summary>
        internal static string GlobalizationGenData {
            get {
                return ResourceManager.GetString("GlobalizationGenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(o.name), rtrim(c.name)
        ///from syscolumns c
        ///inner join sysobjects o on o.id = c.id
        ///where c.status &amp; 128 = 128
        ///and o.name like @prefix.
        /// </summary>
        internal static string IdentityColumns {
            get {
                return ResourceManager.GetString("IdentityColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	rtrim(o.name),
        ///	rtrim(x.name),
        ///	convert(bit, case when indid = 1 then 1 else 0 end), 
        ///	convert(bit, case when x.status &amp; 2 = 2 then 1 else 0 end), 
        ///	isnull(rtrim(g.groupname), &apos;&apos;),
        ///	isnull(rtrim([partition_schema_name]),&apos;&apos;)
        ///from sysobjects o 
        ///inner join sysindexes x on o.id = x.id 
        ///left join sysfilegroups g on x.groupid = g.groupid
        ///left join
        ///(
        ///	select 
        ///		t1.name [TableName],
        ///		ix1.name [indexesName],
        ///		ps1.name [partition_schema_name],
        ///		pf1.name [partition_function_name]
        ///	from 
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(o.name), rtrim(x.name), rtrim(c.name) + &apos;|&apos; + case INDEXKEY_PROPERTY(o.id, x.indid, k.keyno, &apos;IsDescending&apos;) when 0 then &apos;ASC&apos; else &apos;DESC&apos; end
        ///from sysobjects o 
        ///inner join sysindexes x on o.id = x.id 
        ///inner join sysindexkeys k on k.id = x.id and k.indid = x.indid
        ///inner join syscolumns c on c.id = k.id and c.colid = k.colid
        ///where o.type = &apos;U&apos; 
        ///and x.status &amp; 2048 = 0 
        ///and x.status &amp; 4096 = 0 
        ///and x.indid between 1 and 254
        ///and o.name &lt;&gt; &apos;dtproperties&apos; 
        ///and x.name not like &apos;_wa_sys%&apos; 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndexKeys {
            get {
                return ResourceManager.GetString("IndexKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select object_name(o.id), c.text
        ///from syscomments c
        ///	inner join sysobjects o on o.id = c.id and o.xtype = &apos;P&apos; and o.name not like &apos;dt_%&apos;
        ///where o.name like @prefix
        ///order by c.id, c.colid.
        /// </summary>
        internal static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	rtrim(c.table_name), 
        ///	rtrim(c.column_name), 
        ///	rtrim(c.data_type), 
        ///	c.character_maximum_length, 
        ///	rtrim(c.is_nullable), 
        ///	c.ordinal_position, 
        ///	rtrim(c.column_default),
        ///	c.numeric_precision,
        ///	c.numeric_scale,
        ///	--isnull(cc.is_computed,0)  as is_computed,
        ///	isnull(cc.is_persisted,0) as is_persisted,
        ///	cc.definition
        ///from 
        ///	information_schema.columns c
        ///	inner join information_schema.tables t on c.table_name = t.table_name
        ///	left join sys.computed_columns cc on c.COLUMN_NAME = cc.name
        ///whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableColumns {
            get {
                return ResourceManager.GetString("TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(name) from sysobjects
        ///where type = &apos;U&apos;
        ///and name like @prefix
        ///order by crdate.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(t.name), object_name(c.id), c.text
        ///from syscomments c
        ///	inner join sysobjects o on o.id = c.id and o.xtype = &apos;TR&apos; and o.name not like &apos;dt_%&apos;
        ///	inner join sysobjects t on o.parent_obj = t.id
        ///where t.name like @prefix
        ///order by c.id, c.colid.
        /// </summary>
        internal static string Triggers {
            get {
                return ResourceManager.GetString("Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to truncate table orb_Globalization.
        /// </summary>
        internal static string TruncateGlobalization {
            get {
                return ResourceManager.GetString("TruncateGlobalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select rtrim(o.name), c.text
        ///from syscomments c
        ///	inner join sysobjects o on o.id = c.id and o.xtype = &apos;V&apos; and o.name not like &apos;dt_%&apos; and o.name not like &apos;sys%&apos;
        ///where o.name like @prefix
        ///order by c.id, c.colid.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
